(define (problem BLOCKS-10-0)
(:domain BLOCKS)
(:objects GREEN RED PINK PURPLE ORANGE BLACK CYAN WHITE BLUE YELLOW )
 
(:INIT (ONTABLE RED) (ONTABLE ORANGE) (ONTABLE YELLOW) (ONTABLE GREEN) (ONTABLE CYAN) (ONTABLE BLUE) (ONTABLE PURPLE) (ONTABLE PINK) (ONTABLE WHITE) (ONTABLE BLACK)(CLEAR RED)         (HANDEMPTY)) 
(:goal (AND (HOLDING RED) (ONTABLE ORANGE) (ONTABLE YELLOW) (ONTABLE GREEN) (ONTABLE CYAN) (ONTABLE BLUE) (ONTABLE PURPLE) (ONTABLE PINK) (ONTABLE WHITE) (ONTABLE BLACK)         )))