(define (problem BLOCKS-10-0)
(:domain BLOCKS)
(:objects GREEN RED PINK PURPLE ORANGE BLACK CYAN WHITE BLUE YELLOW )
 
(:INIT (ON RED ORANGE) (ONTABLE ORANGE) (ONTABLE WHITE) (ONTABLE BLUE) (ONTABLE YELLOW) (ONTABLE BLACK) (ONTABLE CYAN) (ONTABLE PURPLE) (ONTABLE GREEN) (ONTABLE PINK)(CLEAR BLUE) (CLEAR BLACK)  (CLEAR GREEN) (CLEAR CYAN) (CLEAR YELLOW) (CLEAR PINK) (CLEAR PURPLE) (CLEAR WHITE) (CLEAR RED)(HANDEMPTY)) 
(:goal (AND (ONTABLE RED) (ON ORANGE RED) (ONTABLE WHITE) (ONTABLE BLUE) (ONTABLE YELLOW) (ONTABLE BLACK) (ONTABLE CYAN) (ONTABLE PURPLE) (ONTABLE GREEN) (ONTABLE PINK)(CLEAR BLUE) (CLEAR BLACK) (CLEAR ORANGE) (CLEAR GREEN) (CLEAR CYAN) (CLEAR YELLOW) (CLEAR PINK) (CLEAR PURPLE) (CLEAR WHITE) (HANDEMPTY))))