(define (problem BLOCKS-10-0)
(:domain BLOCKS)
(:objects GREEN RED PINK PURPLE ORANGE BLACK CYAN WHITE BLUE YELLOW )
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
(:INIT 
(:INIT (ONTABLE RED) (ONTABLE ORANGE) (ONTABLE WHITE) (ONTABLE BLUE) (ONTABLE YELLOW) (ONTABLE BLACK) (ONTABLE CYAN) (ONTABLE PURPLE) (ONTABLE GREEN) (ONTABLE PINK)(CLEAR PINK) (CLEAR WHITE) (CLEAR PURPLE) (CLEAR RED) (CLEAR GREEN) (CLEAR CYAN) (CLEAR YELLOW) (CLEAR ORANGE) (CLEAR BLACK) (CLEAR BLUE)(HANDEMPTY))
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
(:goal (AND (ONTABLE RED) (ONTABLE ORANGE) (ONTABLE WHITE) (ONTABLE BLUE) (ONTABLE YELLOW) (ONTABLE BLACK) (ONTABLE CYAN) (ONTABLE PURPLE) (ONTABLE GREEN) (ONTABLE PINK)(CLEAR PINK) (CLEAR WHITE) (CLEAR PURPLE) (CLEAR RED) (CLEAR GREEN) (CLEAR CYAN) (CLEAR YELLOW) (CLEAR ORANGE) (CLEAR BLACK) (CLEAR BLUE)(HANDEMPTY)))) (AND (ONTABLE RED) (ONTABLE ORANGE) (ONTABLE WHITE) (ONTABLE BLUE) (ONTABLE YELLOW) (ONTABLE BLACK) (ONTABLE CYAN) (ONTABLE PURPLE) (ONTABLE GREEN) (ONTABLE PINK)(CLEAR PINK) (CLEAR WHITE) (CLEAR PURPLE) (CLEAR RED) (CLEAR GREEN) (CLEAR CYAN) (CLEAR YELLOW) (CLEAR ORANGE) (CLEAR BLACK) (CLEAR BLUE)(HANDEMPTY))))